---
- name: Import the public key used by the package management system
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=9DA31620334BD75D9DCB49F368818C72E52529D4 state=present

- name: Add MongoDB repository
  apt_repository: repo='deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list' state=present

- name: install mongodb
  apt:
   name: mongodb-org
   state: latest

- name: start the service
  service:
    name: mongodb
    state: started 
  
