---

- name: Update APT package cache
  action: apt update_cache=yes

- name: Download jdk-9.0.4_linux-x64_bin.tar.gz file 
  get_url:
    url: https://javapackage12.s3.ap-south-1.amazonaws.com/jdk-9.0.4_linux-x64_bin.tar.gz
    dest: /home/ubuntu

- name: Extract jdk.tar.gz into /usr/bin
  unarchive:
    src: /home/ubuntu/jdk-9.0.4_linux-x64_bin.tar.gz
    dest: /usr/bin

- name: Set JAVA_HOME
  lineinfile:
    dest: /root/.bashrc
    state: present
    regexp: '^JAVA_HOME'
    line: 'export PATH=$PATH:/usr/bin/jdk-9.0.4/bin'
